"""drop refresh

Revision ID: 76d2178228f3
Revises: 
Create Date: 2022-11-05 15:51:44.020831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d2178228f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_spotify')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('refresh_spotify', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
