"""spotify

Revision ID: aa20abc765b2
Revises: 
Create Date: 2022-11-05 13:53:32.716225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa20abc765b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_spotify', sa.String(), nullable=True))
    op.add_column('user', sa.Column('access_spotify_expires', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('refresh_spotify', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'refresh_spotify')
    op.drop_column('user', 'access_spotify_expires')
    op.drop_column('user', 'access_spotify')
    # ### end Alembic commands ###
